import { VercelRequest, VercelResponse } from '@vercel/node';
import { GoogleGenAI } from "@google/genai";

export default async function handler(req: VercelRequest, res: VercelResponse) {
  // CORS headers
  res.setHeader('Access-Control-Allow-Credentials', 'true');
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET,OPTIONS,PATCH,DELETE,POST,PUT');
  res.setHeader(
    'Access-Control-Allow-Headers',
    'X-CSRF-Token, X-Requested-With, Accept, Accept-Version, Content-Length, Content-MD5, Content-Type, Date, X-Api-Version'
  );

  if (req.method === 'OPTIONS') {
    res.status(200).end();
    return;
  }

  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method Not Allowed' });
  }

  try {
    const { userImage, item, customGarment } = req.body;
    const apiKey = process.env.GEMINI_API_KEY;

    if (!apiKey) {
      return res.status(500).json({ error: "GEMINI_API_KEY is missing. Please set it in your environment variables." });
    }

    const ai = new GoogleGenAI({ apiKey });
    const parts: any[] = [];

    // Helper to get base64
    const getBase64 = async (input: string) => {
      if (input.startsWith('data:')) return input.split(',')[1];
      const response = await fetch(input);
      const buffer = await response.arrayBuffer();
      return Buffer.from(buffer).toString('base64');
    };

    const userBase64 = await getBase64(userImage);
    parts.push({
      inlineData: {
        data: userBase64,
        mimeType: 'image/png',
      },
    });

    if (item.isCustom && customGarment) {
      const garmentBase64 = await getBase64(customGarment);
      parts.push({
        inlineData: {
          data: garmentBase64,
          mimeType: 'image/png',
        },
      });
      parts.push({
        text: `This is a photo of a person and a photo of a garment. Please virtually overlay the garment from the second photo onto the person in the first photo. Ensure the garment fits naturally on their body. Maintain the original person's features and background while seamlessly integrating the new clothing. The final image should look like a real photo of them wearing the garment.`,
      });
    } else {
      parts.push({
        text: `This is a photo of a person. Please virtually overlay this item: "${item.name}" (${item.description}) onto the person in the photo. Ensure the item fits naturally on their body/face. Maintain the original person's features and background while seamlessly integrating the new clothing/accessory. The final image should look like a real photo of them wearing the item.`,
      });
    }

    console.log("Calling Gemini AI...");
    let response;
    try {
      response = await ai.models.generateContent({
        model: 'gemini-2.5-flash-image',
        contents: { parts },
      });
    } catch (firstError: any) {
      const errStr = JSON.stringify(firstError).toLowerCase();
      if (errStr.includes('429') || errStr.includes('quota') || errStr.includes('resource_exhausted')) {
        console.log("Gemini 2.5 Rate Limited. Trying fallback to Gemini 3.1...");
        try {
          response = await ai.models.generateContent({
            model: 'gemini-3.1-flash-image-preview',
            contents: { parts },
          });
        } catch (secondError: any) {
          console.error("Fallback to Gemini 3.1 also failed:", secondError);
          return res.status(429).json({ 
            error: "The AI service is currently at its free-tier limit. Please wait about 60 seconds and try again." 
          });
        }
      } else {
        console.error("Gemini API Error:", firstError);
        return res.status(500).json({ error: firstError.message || "AI processing failed." });
      }
    }

    const candidates = response.candidates;
    if (candidates && candidates.length > 0 && candidates[0].content?.parts) {
      for (const part of candidates[0].content.parts) {
        if (part.inlineData) {
          return res.json({ resultImage: `data:image/png;base64,${part.inlineData.data}` });
        }
      }
    }

    throw new Error("No image generated by AI.");
  } catch (error: any) {
    console.error("Try-on API Error:", error);
    const errStr = JSON.stringify(error).toLowerCase();
    if (errStr.includes('429') || errStr.includes('quota')) {
      return res.status(429).json({ error: "Rate limit reached. Please wait a moment." });
    }
    res.status(500).json({ error: error.message || "Internal Server Error" });
  }
}
