import { VercelRequest, VercelResponse } from '@vercel/node';
import { GoogleGenAI } from "@google/genai";

export default async function handler(req: VercelRequest, res: VercelResponse) {
  // CORS headers
  res.setHeader('Access-Control-Allow-Credentials', 'true');
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET,OPTIONS,PATCH,DELETE,POST,PUT');
  res.setHeader(
    'Access-Control-Allow-Headers',
    'X-CSRF-Token, X-Requested-With, Accept, Accept-Version, Content-Length, Content-MD5, Content-Type, Date, X-Api-Version'
  );

  if (req.method === 'OPTIONS') {
    res.status(200).end();
    return;
  }

  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method Not Allowed' });
  }

  try {
    const { userImage, item, customGarment } = req.body;
    const apiKey = process.env.GEMINI_API_KEY;

    if (!apiKey) {
      return res.status(500).json({ error: "GEMINI_API_KEY is missing. Please set it in your environment variables." });
    }

    const ai = new GoogleGenAI({ apiKey });
    const parts: any[] = [];

    // Helper to get base64
    const getBase64 = async (input: string) => {
      if (input.startsWith('data:')) return input.split(',')[1];
      const response = await fetch(input);
      const buffer = await response.arrayBuffer();
      return Buffer.from(buffer).toString('base64');
    };

    const userBase64 = await getBase64(userImage);
    parts.push({
      inlineData: {
        data: userBase64,
        mimeType: 'image/png',
      },
    });

    if (item.isCustom && customGarment) {
      const garmentBase64 = await getBase64(customGarment);
      parts.push({
        inlineData: {
          data: garmentBase64,
          mimeType: 'image/png',
        },
      });
      parts.push({
        text: "Please virtually overlay the garment from the second photo onto the person in the first photo.",
      });
    } else {
      parts.push({
        text: `Please virtually overlay this item: "${item.name}" onto the person in the photo.`,
      });
    }

    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: { parts },
    });

    const candidates = response.candidates;
    if (candidates && candidates.length > 0 && candidates[0].content?.parts) {
      for (const part of candidates[0].content.parts) {
        if (part.inlineData) {
          return res.json({ resultImage: `data:image/png;base64,${part.inlineData.data}` });
        }
      }
    }

    throw new Error("No image generated by AI.");
  } catch (error: any) {
    console.error("Try-on API Error:", error);
    res.status(500).json({ error: error.message || "Internal Server Error" });
  }
}
